### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by hadim** [butterproject/butter-desktop-angular#11]
Any angular expert around to tell us wether is a smart move to use angular2 ?

I read on various blog that angular 1.x.x is being abandonned (the project started in 2009) partly because of the almost ready to be released ECMAScript 6.

Angular2 seems to be faster an easier to use. Being a really beginner in JS code I am not sure I am true here, I read it on various blogs.

Any comments would be appreciated.

**Comment by BoLaMN** [comment]
I'd beg to differ, angular 2 is still early alpha stage and is recommended to use TypeScript. 

My thoughts when I wrote this was to wait till RC and see what the migration path is.

**Comment by hadim** [comment]
Ok. It's the answer I was looking for !

**Comment by nordjac** [comment]
Interesting reading to take into consideration for preparing for Angular 2.

http://blog.thoughtram.io/angular/2015/10/24/upgrading-apps-to-angular-2-using-ngupgrade.html
