### ISSUE TITLE
multi API [feature]

### ISSUE THREAD

**Issue by mama21mama** [butterproject/butter-desktop-angular#16]
Backup server in another nation to feed the API.

Server 1 > API
Server 2 [mirror] > API

Status Project > Server 1
Status Project > Server 2 [mirror]

**Comment by hadim** [comment]
If you are talking about server that provide torrents such as vodo, backup server will probably be coded in plugins.

But we are still far from here :-)

**Comment by BoLaMN** [comment]
See plugin-manager folder. I did start on it.

**Comment by hadim** [comment]
Yeah I saw that but it's hard to understand :-)
