### ISSUE TITLE
Put "illegal sites" plugins in some other repo/package

### ISSUE THREAD

**Issue by rom1504** [butterproject/butter-desktop-angular#48]
https://github.com/butterproject/butter-desktop-angular/tree/master/src/client/plugins-manager/plugins

That's if you want to avoid getting DMCA'd. Up to you.

**Comment by paularchive** [comment]
Issue opened in wrong repo

**Comment by rom1504** [comment]
No, look at the url.

**Comment by paularchive** [comment]
Oh nvm sorry was my browsers fault

**Comment by MrAdder** [comment]
We will be
