### ISSUE TITLE
AngularJS + Angular Material from npm

### ISSUE THREAD

**Issue by z11h** [butterproject/butter-desktop-angular#56]
I was wondering why the application does not get AngularJS and Angular Material from npm now that Google has started providing Angular on npm. 

I am willing to provide a PR that moves the application to using npm for AngularJS and Angular Material.

Another big bonus is that it really helps decrease the friction the app goes through to update Angular/ rolling back to an earlier version.

Thanks! :smile_cat:

**Comment by xaiki** [comment]
sure !

**Comment by hadim** [comment]
I also agree on that.

**Comment by z11h** [comment]
@hadim PR incoming :smile:
