### ISSUE TITLE
Why the coffee dialect? 

### ISSUE THREAD

**Issue by NoNameProvided** [butterproject/butter-desktop-angular#65]
It not so widely adopted, and I think it prevents users from contributing to to project. (eg me) Why don't you use the ES6 'dialect'? 

If this question is open to discussion, I can go in more detail, but I dont want to write lengthy issue if there is no chance to change on this.

**Comment by xaiki** [comment]
it's actually an old project (that stagnated for a while) and it was made using coffee, we have a lot of code already written, if you want to continue on this, send a PR converting all to ES6 =)

**Comment by NoNameProvided** [comment]
Old? If I understand correctly this project should replace the old butter client what is based on NW.js and some other js framework.

**Comment by z11h** [comment]
@NoNameProvided yes, this project is to replace the old butter project but what @xaiki means to say is that it hasn't been in active dev for a while. 

I was actually contemplating moving to ES6 over coffeescript, and if you want we can work together to convert the whole project to standard JS ES6. 

It would make the whole project less alienating to newcomers that want to contribute :smile:

**Comment by hadim** [comment]
That would be really cool to do that !

**Comment by NoNameProvided** [comment]
If I recall correctly,  you have a slack team for  talking about butter right? Lets talk about the details there. I don't want to expose my email here, so could it work if I just sent it to you @ZakariaRidouh? (Through your website contact form)

**Comment by xaiki** [comment]
slack is for active members day to day cooperation, we prefer to have most important talk in the open.

**Comment by z11h** [comment]
@NoNameProvided Yes, you can just send me a message using the form on my website (it should work now). Also, we can use this thread for open discussion (ill ask xaiki about the slack).

Thanks for helping out! :smile:

**Comment by NoNameProvided** [comment]
@xaiki its funny to say dat to day operations when in the last three months @ZakariaRidouh was the only who took the effort to contribute to the repo. 

But its ok for me to keep this discussion here, (and in new issues) but having long conversations here will be super slow because of our different time zones.  

I will come up with a new ticket soon about the things I have in my mind now.
